# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperfindicator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a5c9bf68b8774e5ab386511169fba133 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_99b7e2e100bf4b8797347630c0a9668c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a5c9bf68b8774e5ab386511169fba133 }}/ananthakrishnank/studperfindicator:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperfindicator'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_29c54aa2ba0a4037aedccf1edeb5f1ad }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a5c9bf68b8774e5ab386511169fba133 }}/ananthakrishnank/studperfindicator:${{ github.sha }}'